/**
 * Version Information for Joanie's Kitchen
 *
 * Auto-generated by scripts/version.ts
 * DO NOT EDIT MANUALLY
 */

export const VERSION = '0.7.10';
export const BUILD = 245;
export const BUILD_DATE = '2026-02-17T02:05:30.117Z';

export interface VersionInfo {
  version: string;
  build: number;
  buildDate: string;
}

export function getVersionInfo(): VersionInfo {
  return {
    version: VERSION,
    build: BUILD,
    buildDate: BUILD_DATE,
  };
}

export function getVersionString(): string {
  return `v${VERSION} (build ${BUILD})`;
}

export function getShortVersion(): string {
  return VERSION;
}
